In [41]:
import cv2
import numpy as np
from PIL import Image

In [43]:
# Load image

image = Image.open('road.jpg')
new_image = image.resize((500, 500))
new_image.save('road.jpg')

image = cv2.imread('road.jpg')

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# Show the result
cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [44]:
# Show the result
cv2.imshow('Result', gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
# Convert image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
# Define our parameters for Canny
low_threshold = 50
high_threshold = 100
edges = cv2.Canny(gray, low_threshold, high_threshold)
# Show the result
cv2.imshow('edges', edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [77]:
# Define the Hough transform parameters
# Make a blank the same size as our image to draw on
rho = 1
theta = np.pi/180
threshold = 200
min_line_length = 200
max_line_gap = 30
line_image = np.copy(image) #creating an image copy to draw lines on
# Run Hough on the edge-detected image
lines = cv2.HoughLinesP(edges, rho, theta, threshold, np.array([]),
                        min_line_length, max_line_gap)
# Iterate over the output "lines" and draw lines on the image copy
for line in lines:
    for x1,y1,x2,y2 in line:
        cv2.line(line_image,(x1,y1),(x2,y2),(255,0,0),5)
        
# Show the result
cv2.imshow('line_image', line_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
# Draw lines on the image
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

# Show the result
cv2.imshow('Result', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:

img = cv2.imread('traffic.jpg')
img2 = img.copy()
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.GaussianBlur(image, (7, 7), 1.5)
img = cv2.Canny(img, 50, 120)

cv2.imwrite("‘img_morph8.png’", img)
print(img.shape)
h, w = img.shape[:]

cv2.imshow("“image”", img)
circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT, 1.5, int(w / 20), param1=50, param2=20, minRadius=int(w / 40),
maxRadius=int(w / 15))

circles = np.uint16(np.around(circles))

for c in circles[0, :]:
    print(c)
    cv2.circle(img2, (c[0], c[1]), c[2], (0, 255, 0), 2)
    cv2.circle(img2, (c[0], c[1]), 1, (0, 0, 255), 1)

    cv2.imshow("output img", img2)
    cv2.waitKey(0)
    cv2.imwrite("“houghcircle-ex8.png”", img2)

(408, 612)
[259 325  36]
[127 124  39]
[ 86 139  39]
[196 131  39]
[88 73 39]
[257 199  38]
[259  73  38]
[110 202  39]
[130 154  39]
[508 185  39]
[127 283  39]
[160 136  39]
[199 233  39]
[ 53 205  39]
[ 56 142  39]
[127  94  39]
[187  85  39]
[ 91 109  38]
[184 187  39]
[ 56 367  39]
[91 40 39]
[106 358  39]
[ 56 172  39]
[ 65 274  34]
[544 191  38]
[127 253  39]
[265 109  39]
[586 197  39]
[154  73  38]
[ 98 241  39]
[160 322  39]
[106 325  38]
[172 250  38]
[226 137  39]
[430 196  38]
[ 56 334  34]
[577 163  31]
[ 56 304  39]
[557 352  38]
[550 253  38]
[130  34  39]
[196 367  36]
[38 52 39]
[214 196  39]
[217 260  36]
[ 59 112  39]
[157 277  34]
[460 226  31]
[154 193  39]
[511 241  34]
[ 98 172  29]
[163 103  39]
[511 140  39]
[232 169  38]
[ 65 244  34]
[118  64  29]
[551 382  34]
[ 56 397  39]
[190 328  39]
[ 20 103  39]
[262 139  39]
[508  97  39]
[262 256  36]
[466 148  38]
[391 199  31]
[601 331  29]
[562 220  21]
[178  52  39]
[580 121  39]
[223  76  36]
[32 13 29]
[322 22

In [23]:
import cv2
import numpy as np

image = cv2.imread("traffic.jpg")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blur = cv2.medianBlur(gray, 5)
circles = cv2.HoughCircles(blur, cv2.CV_HOUGH_GRADIENT, 1.5, 10)
for i in circles[0,:]:
       # draw the outer circle
       cv2.circle(image,(i[0], i[1]), i[2], (255, 0, 0), 2)
      
       # draw the center of the circle
       cv2.circle(image, (i[0], i[1]), 2, (0, 255, 0), 5)
cv2.imshow('detected circles', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

AttributeError: module 'cv2' has no attribute 'CV_HOUGH_GRADIENT'

In [ ]:
import numpy as np
import math
import cv2

class HoughTransform:
    
    def __init__(self, image):
        self.image = image
        self.width, self.height = image.shape[:2]
        
    def hough_lines_acc(self, ThetaResolution=1, RhoResolution=1):
        diagonal = math.sqrt(self.width**2 + self.height**2)
        num_thetas = int(np.ceil(180 / ThetaResolution))
        num_rhos = int(np.ceil(2 * diagonal / RhoResolution))
        thetas = np.deg2rad(np.arange(-90, 90, ThetaResolution))
        rhos = np.linspace(-diagonal, diagonal, num_rhos)
        accumulator = np.zeros((num_rhos, num_thetas), dtype=np.uint64)

        # find edge pixels
        edge_indices = np.nonzero(self.image)
        edge_y, edge_x = edge_indices[0], edge_indices[1]

        # accumulate votes for each edge pixel
        for i in range(len(edge_x)):
            x = edge_x[i]
            y = edge_y[i]

            for j in range(len(thetas)):
                rho = x * np.cos(thetas[j]) + y * np.sin(thetas[j])
                rho_idx = np.argmin(np.abs(rhos - rho))
                accumulator[rho_idx, j] += 1

        return accumulator, thetas, rhos
    
    def hough_peaks(self, H, thetas, rhos, threshold=0, n_peaks=np.inf):
        peak_values = []
        peak_locations = []

        # find peaks in the accumulator matrix
        for i in range(H.shape[0]):
            for j in range(H.shape[1]):
                if H[i, j] > threshold:
                    peak_values.append(H[i, j])
                    peak_locations.append((i, j))

        # sort the peaks by their values in descending order
        sorted_peak_indices = np.argsort(peak_values)[::-1]

        # return the top s peaks if specified
        if n_peaks < np.inf:
            sorted_peak_indices = sorted_peak_indices[:n_peaks]

        # return the peak locations and values
        peak_rho, peak_theta = [], []
        for idx in sorted_peak_indices:
            rho_idx, theta_idx = peak_locations[idx]
            peak_rho.append(rhos[rho_idx])
            peak_theta.append(thetas[theta_idx])

        return peak_rho, peak_theta
    
    def hough_lines_draw(self, image, peak_rho, peak_theta):
        for rho, theta in zip(peak_rho, peak_theta):
            a = np.cos(theta)
            b = np.sin(theta)
            x0 = a * rho
            y0 = b * rho
            x1 = int(x0 + 1000 * (-b))
            y1 = int(y0 + 1000 * (a))
            x2 = int(x0 - 1000 * (-b))
            y2 = int(y0 - 1000 * (a))
            cv2.line(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

        return image

In [9]:
import pyautogui as p
import time

time.sleep(4)

for i in range(1000):
    p.typewrite("ali")
    p.press("enter")